---
# InfluxDB playbook
# Clean the Continuous Queries: ansible-playbook influxdb.yml --tags clean_cq -e clean_cq=1
# Uninstall and Clean up InfluxDB : ansible-playbook influxdb.yml --tags clean_influxdb -e clean_influxdb=1
# Do a complete install of Influx DB clusters : ansible-playbook influxdb.yml

- name: Download required files
  hosts: influxdb
  sudo: yes
  run_once: yes
  roles:
   - { role: local-rpms, tags: local-rpms }

- name: Install InfluxDB one by one
  hosts: influxdb
  sudo: yes
  serial: 1
  roles: 
  - { role: influxdb, tags: influxdb }

- name: Create the DATABASES and install the retention policies (NEW)
  hosts: influxdb
  sudo: yes
  roles:
   - { role: influxdb/db, tags: db }
   - { role: influxdb/rp, tags: rp }
   - { role: influxdb/rp, tags: rp, influx_db: "{{ daily_stats_db }}", influx_rp: "{{ daily_stats_rp }}" }
   - { role: influxdb/cq, tags: cq }
   #- { role: influxdb/cq, tags: cq, influx_cq: "{{ test_cq }}" }
